# Generated by Django 4.2 on 2023-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_delete_manager_customuser_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em progresso'), (3, 'Resolvido'), (4, 'Fechado')], default=1),
        ),
    ]
